// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjglvfgkwbzvzjbcqmtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZ2x2Zmdrd2J6dnpqYmNxbXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzgxNzksImV4cCI6MjA3MjM1NDE3OX0.LE5Cr8XI_xFsERECtnrHjYGozcw8Hguntrq5YVM6VMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});